CREATE DATABASE PANADERIA;
USE PANADERIA;

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO VARCHAR(30) NOT NULL PRIMARY KEY,
    Nombre_PRO VARCHAR(100) NOT NULL,
    Descripcion_PRO VARCHAR(150),
    Precio_venta REAL NOT NULL,
    Stock_PRO INT NOT NULL);

CREATE TABLE CLIENTES (
    ID_CLIENTE VARCHAR(30) NOT NULL PRIMARY KEY,
    Nombre_CLI VARCHAR(100) NOT NULL,
    Telefono_CLI VARCHAR(20),
    Direccion_CLI VARCHAR(150),
    Email_CLI VARCHAR(100));

CREATE TABLE EMPLEADOS (
    ID_EMPLEADO VARCHAR(30) NOT NULL PRIMARY KEY,
    Nombre_EMP VARCHAR(100) NOT NULL,
    Apellido_EMP VARCHAR(100) NOT NULL,
    Cargo_EMP VARCHAR(50),
    Salario REAL,
    Afiliacion VARCHAR(30) NOT NULL);
    
CREATE TABLE PROVEEDORES (
    ID_PROVEEDOR VARCHAR(30) NOT NULL PRIMARY KEY,
    Nombre_PROV VARCHAR(100) NOT NULL,
    Telefono_PROV VARCHAR(20),
    Email_PROV VARCHAR(100),
    Direccion_PROV VARCHAR(150),
    Distrito_PROV VARCHAR(50));
    
CREATE TABLE VENTA_DETALLADA 
(
	ID_VENTA VARCHAR(30) PRIMARY KEY,
    ID_CLIENTE VARCHAR(30),
    ID_EMPLEADO VARCHAR(30),
    Fecha_VEN DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_PRODUCTO VARCHAR(30),
    Nombre_PRO VARCHAR(100),
    Cantidad INT,
    Precio_Unitario REAL,
    Subtotal REAL,

    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO));

    
CREATE TABLE COMPRA_PRODUCTOS (
    ID_COMPRA VARCHAR(30) NOT NULL PRIMARY KEY,
    ID_PROVEEDOR VARCHAR(30),
    ID_EMPLEADO VARCHAR(30),
    NOMBRE_PRO VARCHAR(100),
    Fecha_COM_PRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    Cantidad_COM_PRO INT NOT NULL,
    PrecioC_COM_PRO REAL NOT NULL,
    Total_COM_PRO REAL NOT NULL,
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO));
    